// D:\projects\Aura\backend\src\routes\orders.js
const express = require("express");
const router = express.Router();
const Order = require("../models/Order");
const authMiddleware = require("../middleware/auth");

// GET orders for logged-in customer
router.get("/", authMiddleware, async (req, res) => {
  try {
    const orders = await Order.find({ customerId: req.user.id });
    res.json(orders);
  } catch (err) {
    console.error("Fetch orders error:", err);
    res.status(500).json({ message: "Failed to fetch orders" });
  }
});

// CREATE order
router.post("/", authMiddleware, async (req, res) => {
  try {
    const order = new Order({
      customerId: req.user.id,
      vendorId: req.body.vendorId,
      items: req.body.items,
      totalAmount: req.body.totalAmount,
      deliveryAddress: req.body.deliveryAddress
      // OTP will be auto-generated by the default function
    });

    await order.save();
    res.status(201).json(order);

  } catch (err) {
    console.error("Order creation error:", err);
    console.error("Error details:", err.errors); // Shows validation errors
    res.status(400).json({ 
      message: "Order creation failed",
      error: err.message,
      details: err.errors
    });
  }
});
// Get a specific order
router.get("/:id", authMiddleware, async (req, res) => {
  try {
    const order = await Order.findOne({ 
      _id: req.params.id, 
      customerId: req.user.id 
    });
    
    if (!order) {
      return res.status(404).json({ message: "Order not found" });
    }
    
    res.json(order);
  } catch (err) {
    console.error("Fetch order error:", err);
    res.status(500).json({ message: "Failed to fetch order" });
  }
});
// POST /orders/verify
router.post("/verify", authMiddleware, async (req, res) => {
  try {
    const { orderId, otp } = req.body;

    const order = await Order.findOne({ _id: orderId });

    if (!order) {
      return res.status(404).json({ message: "Order not found" });
    }

    if (order.otp !== otp) {
      return res.status(400).json({ message: "Invalid OTP" });
    }

    order.status = "DELIVERED";
    await order.save();

    res.json({ message: "Order delivered successfully" });
  } catch (err) {
    console.error("OTP verify error:", err);
    res.status(500).json({ message: "OTP verification failed" });
  }
});

module.exports = router;